spring.application.name=PEM
server.port=8080
spring.datasource.url=jdbc:postgresql://dpg-d8k61enlk1mc73bu6630-a.singapore-postgres.render.com/pem
spring.datasource.username=pem_user
spring.datasource.password=iNPBKZjaL8ko8TmEu0i4HiZBAaw3I9l0

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.app.secreatKey = "mysupersecreatkey123mysupersecreatkey4567890"

logging.level.org.springframework.security=DEBUG