spring.application.name=PEM
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/pem
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.app.secreatKey = "mysupersecreatkey123mysupersecreatkey4567890"

logging.level.org.springframework.security=DEBUG